### ISSUE TITLE
Can't continue with installation

### ISSUE THREAD

**Issue by kskim7** [mydevilroot/thinkpad-x270-opencore#1]
Hello brother!! 
First of all, thanks for sharing your work!!

I have a question as I faced problem with getting this installed to my X270 with similar settings - i5-7200U, 16GB RAM, and 256GB SSD - the only difference is, the ram size. 

I got the opencore patcher to make the installer USB and put your EFI's into the EFI partition. 
And then, I was able to get into the installation process, so I did install it to my SSD.
And after that, the system reboot, and when I chose the macos install partition installed to my ssd, it soon reboots again. 
It seems, with your EFI's I can get into the installation process, but continuing installation doesn't seem to work.

Any idea what could have been wrong with me??
Should I do something else?

**Comment by QQ-War** [comment]
how you solve it?
